spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
      changeLogPackage: ru.photorex.server.changelog
    rest:
      default-page-size: 10
server:
  port: 8081

